#!/bin/bash

set -e

if [ "$(id -u)" != "0" ]; then
	echo "Superuser privileges are required to run this script." 1>&2
	exit 1
fi

readonly DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )


echo "Copying files ..."

mkdir -p /usr/local/Bluemix/bin/cfcli
mkdir -p /usr/local/Bluemix/bx

cp -f ${DIR}/bin/NOTICE /usr/local/Bluemix/bin/
cp -f ${DIR}/bin/LICENSE /usr/local/Bluemix/bin/
cp -f ${DIR}/bin/bluemix /usr/local/Bluemix/bin/
cp -f ${DIR}/bin/bluemix-analytics /usr/local/Bluemix/bin/
cp -f ${DIR}/bin/cfcli/cf /usr/local/Bluemix/bin/cfcli/
cp -f ${DIR}/bx/bash_autocomplete /usr/local/Bluemix/bx/
cp -f ${DIR}/bx/zsh_autocomplete /usr/local/Bluemix/bx/

ln -sf /usr/local/Bluemix/bin/bluemix /usr/local/Bluemix/bin/bx
ln -sf /usr/local/Bluemix/bin/bluemix /usr/local/bin/bluemix
ln -sf /usr/local/Bluemix/bin/bluemix /usr/local/bin/bx
ln -sf /usr/local/Bluemix/bin/bluemix-analytics /usr/local/bin/bluemix-analytics

chown -R root:root /usr/local/Bluemix
chmod -R 755 /usr/local/Bluemix

function updateConfig()
{
	_file_path=$1
	_key=$2
	_content=$3

	if [ -f $_file_path ] && [ -z "`cat $_file_path | grep $_key`" ]; then
		chmod 666 $_file_path
		echo -e "\n### Added by the Bluemix CLI" >> $_file_path
		echo $_content >> $_file_path
		chmod 644 $_file_path
	fi
}

function updateAutocomplete()
{
	_file_path=$1
	_script=$2
	updateConfig $_file_path "/usr/local/Bluemix/bx/$2" "source /usr/local/Bluemix/bx/$2"
}

# add autocomplete to bash
if [ ! -d "/etc/bash_completion.d" ]; then 
	# login shell
	updateAutocomplete "/etc/profile" "bash_autocomplete"
	# non-login shell
	updateAutocomplete "/etc/bash.bashrc" "bash_autocomplete"
else
	cp -f ${DIR}/bx/bash_autocomplete /etc/bash_completion.d/bluemix_cli_autocomplete
	chown root:root /etc/bash_completion.d/bluemix_cli_autocomplete
	chmod 644 /etc/bash_completion.d/bluemix_cli_autocomplete
fi

# add autocomplete to zsh
updateAutocomplete "/etc/zsh/zshrc" "zsh_autocomplete"

echo "The Bluemix Command Line Interface (Bluemix CLI) is installed successfully."
echo "To get started, open a new Linux terminal and enter \"bluemix help\", or enter \"bx help\" as short name."
echo ""
echo "With Bluemix CLI 0.4.0 or later, the CLI can automatically collect diagnostic and usage information and send it to Bluemix for analysis."
echo "This information will help us better understand current client usage and plan for future use. No personally identifiable data is collected."
echo ""
echo "To stop collecting information, you can run the following command:"
echo "        'bluemix config --usage-stats-collect false'"